name: Deploy React site to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write      # allow the Action to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build

      # ---------- SPA fallback for pretty URLs ----------
      - name: Copy index.html to 404.html
        run: cp build/index.html build/404.html
      # --------------------------------------------------

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
